version: '3'
services:
  caddy:
    image: index.docker.io/caddy/caddy:2-alpine
    restart: always
    container_name: caddy
    ports:
      - 80:80
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/html/:/etc/caddy/html/
    environment:
      ACME_AGREE: 'true'
    depends_on:
      - db
      - adamrms
  db:
    image: index.docker.io/mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-thread-concurrency=0 --sort_buffer_size=512K
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_DATABASE=${bCMS__DB_DATABASE}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${bCMS__DB_USERNAME}
      - MYSQL_PASSWORD=${bCMS__DB_PASSWORD}
    env_file:
      - .env
  adamrms:
    image: ghcr.io/adam-rms/adam-rms:latest
    container_name: adamrms
    restart: always
    depends_on:
      - db
    environment:
      - bCMS__DB_HOSTNAME=${bCMS__DB_HOSTNAME}
      - bCMS__DB_DATABASE=${bCMS__DB_DATABASE}
      - bCMS__DB_USERNAME=${bCMS__DB_USERNAME}
      - bCMS__DB_PASSWORD=${bCMS__DB_PASSWORD}
    env_file:
      - .env
  adamrms_staticfiles:
    build:
      context: .
      dockerfile: ./staticfiles.Dockerfile
    container_name: adamrms_static
    restart: always
  compressor:
    image: ghcr.io/adam-rms/adam-rms-imagecompressor/main:latest
    restart: always
    container_name: compressor
    depends_on:
      - db
    environment:
      - MYSQL_HOSTNAME=${bCMS__DB_HOSTNAME}
      - MYSQL_DATABASE=${bCMS__DB_DATABASE}
      - MYSQL_USER=${bCMS__DB_USERNAME}
      - MYSQL_PASSWORD=${bCMS__DB_PASSWORD}
      - SLEEP_TIME=60
    env_file:
      - .env
  deletor:
    image: ghcr.io/adam-rms/adam-rms-s3deletor/main:latest
    restart: always
    container_name: deletor
    depends_on:
      - db
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=${bCMS__DB_DATABASE}
      - MYSQL_USER=${bCMS__DB_USERNAME}
      - MYSQL_PASSWORD=${bCMS__DB_PASSWORD}
      - SLEEP_TIME=600
    env_file:
      - .env

volumes:
  db_data: { }
